name: Stage deployment

on:
  pull_request:
    branches:
      - stage 
    types:
      - closed

env:
  environment: "stage"

jobs:
  Deployment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
    - name: Check out to main branch.
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          hectormedinanubosas/demo-nomad-job:${{ env.environment }}_latest
          hectormedinanubosas/demo-nomad-job:${{ env.environment }}_${{ github.sha }}
    - name: Update nomad job.
      run: |
        # Prepare hcl file.
        export payload=$(jq -Rsc '{JobHCL: ., Canonicalize: true}' nomad/stage/turisapps_web_${{ env.environment }}.hcl)
        # Get the json file.
        export payload_json=$(curl -H 'Content-Type: application/json'  \
                                   -X POST http://nomad.hectormedina.es/v1/jobs/parse \
                                   -d "$payload")
        # Update job with json.
        export http_code=$(curl \
                                -H 'Content-Type: application/json'  \
                                -X POST \
                                http://nomad.hectormedina.es/v1/job/turisapps_web_${{ env.environment }} \
                                -d "{\"Job\": $payload_json }" )
        echo "$http_code"
        # Check if update was successful. 
        if [ "$http_code" != "200" ]
        then
          echo "::error:: Nomad job create HTTP response code : $CODE"
          # Fail the job.
          exit 1
        fi