name: Stage deployment

on:
  pull_request:
    branches:
      - main 
    types:
      - closed

jobs:
  Build_and_push_to_registry:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
    - name: Check out to main branch.
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          hectormedinanubosas/demo-nomad-job:latest
          hectormedinanubosas/demo-nomad-job:${{ github.sha }}
    - name: Get valid json from hcl file.
      id: valid_json
      run: |
        export PAYLOAD=$(jq -Rsc '{JobHCL: ., Canonicalize: true}' nomad/stage/app.hcl)
        export PAYLOAD_JSON=$(curl -H 'Content-Type: application/json'  \
                                   -X POST http://nomad.hectormedina.es/v1/jobs/parse \
                                   -d "$payload")
        echo "variable=$PAYLOAD_JSON" >> $GITHUB_ENV
    - name: Update nomad job.
      run: |
        echo ${{ env.variable }}
        export http_code=$(curl --write-out '%{http_code}' --silent --output /dev/null \
                                  -H 'Content-Type: application/json'  \
                                  -X POST \
                                  http://nomad.hectormedina.es/v1/jobs \
                                  -d "{\"Job\": ${{ env.variable }} }" )
        if [ "$http_code" != "200" ]
        then
          echo "::error:: Nomad job create HTTP response code : $CODE"
          # Fail the job.
          exit 1
        fi

