name: Stage deployment

on:
  pull_request:
    branches:
      - main 
    types:
      - closed

jobs:
  Build_and_push_to_registry:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
    - name: Check out to main branch.
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          hectormedinanubosas/demo-nomad-job:latest
          hectormedinanubosas/demo-nomad-job:${{ github.sha }}
    - name: test jq native
      run: |
        jq -Rsc '{JobHCL: ., Canonicalize: true}' nomad/stage/app.hcl
    
    - name: Use JQ to get valid json to parse.
      uses: sergeysova/jq-action@v2
      id: jq
      with:
        cmd: "jq -Rsc '{JobHCL: ., Canonicalize: true}' nomad/stage/app.hcl"
    - name: Convert hcl to json
      run: |
        export status_code=$(curl --write-out '%(http_code)' --silent --output /dev/null \
                                  -H 'Content-Type: application/json'  \
                                  -X POST \
                                  http://nomad.hectormedina.es/v1/jobs/parse \
                                  -d @{{ github.repository }}/nomad/stage/php.hcl
        )
        echo "::warning::HTTP status code from grafana API: $CODE"


